name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.4.0
        with:
          linter: pylint          